CREATE TABLE IF NOT EXISTS health_checks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS photo_assets (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    original_path VARCHAR(255) NOT NULL,
    thumbnail_path VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    alt_text VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    mime_type VARCHAR(50) NOT NULL,
    width INT UNSIGNED NOT NULL,
    height INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS poems (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    written_date DATE NOT NULL,
    description MEDIUMTEXT NOT NULL,
    content MEDIUMTEXT NOT NULL,
    parent_poem_id INT UNSIGNED NULL,
    photo_id INT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_poems_parent FOREIGN KEY (parent_poem_id) REFERENCES poems (id) ON DELETE SET NULL,
    CONSTRAINT fk_poems_photo FOREIGN KEY (photo_id) REFERENCES photo_assets (id) ON DELETE SET NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS publishers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NULL,
    url VARCHAR(2048) NULL,
    telephone VARCHAR(50) NULL,
    email VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS publisher_contacts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    publisher_id INT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    telephone VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_publisher_contacts_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS submissions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    poem_id INT UNSIGNED NOT NULL,
    publisher_id INT UNSIGNED NULL,
    publisher_name VARCHAR(255) NULL,
    publisher_contact_name VARCHAR(255) NULL,
    publisher_contact_id INT UNSIGNED NULL,
    call_name VARCHAR(255) NOT NULL,
    submission_url VARCHAR(2048) NULL,
    closing_date DATE NOT NULL,
    submitted_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_submissions_poem FOREIGN KEY (poem_id) REFERENCES poems (id) ON DELETE CASCADE,
    CONSTRAINT fk_submissions_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id) ON DELETE SET NULL,
    CONSTRAINT fk_submissions_contact FOREIGN KEY (publisher_contact_id) REFERENCES publisher_contacts (id) ON DELETE SET NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS poem_categories (
    poem_id INT UNSIGNED NOT NULL,
    category_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (poem_id, category_id),
    CONSTRAINT fk_poem_categories_poem FOREIGN KEY (poem_id) REFERENCES poems (id) ON DELETE CASCADE,
    CONSTRAINT fk_poem_categories_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS volumes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description MEDIUMTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS volume_poems (
    volume_id INT UNSIGNED NOT NULL,
    poem_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (volume_id, poem_id),
    CONSTRAINT fk_volume_poems_volume FOREIGN KEY (volume_id) REFERENCES volumes (id) ON DELETE CASCADE,
    CONSTRAINT fk_volume_poems_poem FOREIGN KEY (poem_id) REFERENCES poems (id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
